version: 2

steps-build: &steps-build
  docker:
    - image: circleci/python:2.7-buster
  resource_class: 2xlarge
  steps:
    - checkout
    - run: sudo pip install s3cmd
    - run: sudo apt install -y binutils-arm-linux-gnueabi binutils-arm-linux-gnueabihf binutils-mips64el-linux-gnuabi64 binutils-mipsel-linux-gnu
    - restore_cache:
        keys:
          - deps-v2-
    - run:
        name: Fix the freetype stuff, idek
        command:  |
          if [[ -d out/sysroot-build/sid/debian-packages]]; then
            rm out/sysroot-build/sid/debian-packages/libfreetype6*
          fi
    - run:
        name: Build and Upload
        command: ./build/linux/sysroot_scripts/build_and_upload.py
        no_output_timeout: 60m
    - save_cache:
        key: deps-v2-{{ .Revision }}
        paths:
          - out/sysroot-build/sid/debian-packages
    - store_artifacts:
        path: build/linux/sysroot_scripts/sysroots.json
        destination: sysroots.json

jobs:
  build:
    <<: *steps-build

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build
