version: 2

steps-build: &steps-build
  docker:
    - image: circleci/python:2.7-stretch
  resource_class: 2xlarge
  steps:
    - checkout
    - run: sudo pip install s3cmd
    - restore_cache:
        keys:
          - deps-v2-
    - run: ./build/linux/sysroot_scripts/build_and_upload.py
    - save_cache:
        key: deps-v2-{{ .Revision }}
        paths:
          - out/sysroot-build/sid/debian-packages
    - store_artifacts:
        path: build/linux/sysroot_scripts/sysroots.json
        destination: sysroots.json

jobs:
  build:
    <<: *steps-build

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build
