version: 2.1

steps-build: &steps-build
  docker:
    - image: circleci/python:2.7-stretch
  resource_class: 2xlarge
  steps:
    - checkout
    - run: sudo pip install s3cmd
    - restore_cache:
        keys:
          - deps-v1-{{ .Environment.ElectronSingleArch }}
    - run: ./build/linux/sysroot_scripts/build_and_upload.py
    - save_cache:
        key: deps-v1-{{ .Environment.ElectronSingleArch }}-{{ .Revision }}
        paths:
          - out/sysroot-build/sid/debian-packages
    - store_artifacts:
        path: build/linux/sysroot_scripts/sysroots.json
        destination: sysroots.json

jobs:
  build-amd64:
    environment:
      ElectronSingleArch: Amd64
    <<: *steps-build
  build-i386:
    environment:
      ElectronSingleArch: I386
    <<: *steps-build
  build-arm:
    environment:
      ElectronSingleArch: ARM
    <<: *steps-build
  build-arm64:
    environment:
      ElectronSingleArch: ARM64
    <<: *steps-build
  build-armel:
    environment:
      ElectronSingleArch: ARMEL
    <<: *steps-build
  build-mips:
    environment:
      ElectronSingleArch: Mips
    <<: *steps-build
  build-mips64el:
    environment:
      ElectronSingleArch: Mips64el
    <<: *steps-build


workflows:
  version: 2.1
  build-and-upload:
    jobs:
      - build-amd64
      - build-i386
      - build-arm
      - build-arm64
      - build-armel
      - build-mips
      - build-mips64el
